-- MySQL Script generated by MySQL Workbench
-- Mon Feb 26 00:21:20 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema otakeros
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema otakeros
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `otakeros` DEFAULT CHARACTER SET utf8 ;
USE `otakeros` ;

-- -----------------------------------------------------
-- Table `otakeros`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `otakeros`.`tipo_usuario` (
  `id_tipo` INT NOT NULL,
  `nome_tipo` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `otakeros`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `otakeros`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `idade` INT NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(50) NOT NULL,
  `avatar` VARCHAR(50) NULL,
  `id_tipo` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_id_tipo_idx` (`id_tipo` ASC) VISIBLE,
  CONSTRAINT `fk_id_tipo`
    FOREIGN KEY (`id_tipo`)
    REFERENCES `otakeros`.`tipo_usuario` (`id_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `otakeros`.`anime`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `otakeros`.`anime` (
  `id_anime` INT NOT NULL AUTO_INCREMENT,
  `nome_anime` VARCHAR(50) NOT NULL,
  `descricao_anime` TEXT NOT NULL,
  `imagem_anime` VARCHAR(50) NULL,
  PRIMARY KEY (`id_anime`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `otakeros`.`episodio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `otakeros`.`episodio` (
  `id_episodio` INT NOT NULL AUTO_INCREMENT,
  `id_numero_episodio` INT NOT NULL,
  `nome_episodio` VARCHAR(100) NOT NULL,
  `video_url_episodio` TEXT NOT NULL,
  `id_anime` INT NOT NULL,
  PRIMARY KEY (`id_episodio`),
  INDEX `fk_id_anime_idx` (`id_anime` ASC) VISIBLE,
  UNIQUE INDEX `id_numero_episodio_UNIQUE` (`id_numero_episodio` ASC) VISIBLE,
  CONSTRAINT `fk_id_anime`
    FOREIGN KEY (`id_anime`)
    REFERENCES `otakeros`.`anime` (`id_anime`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
